### ISSUE TITLE
Typo in README

### ISSUE THREAD

**Issue by James-Firth** [linuxserver/docker-apprise-api#7]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

> Send notifications to more then 65+ services.

should become

> Send notifications to more than 65+ services.

### Reason for change

Incorrect wording

### Proposed code change

Line 9 of `readme-vars.yml` should say 
```markdown
  * Send notifications to more than 65+ services.
  ```

**Comment by aptalca** [comment]
> Send notifications to more than 65+ services.
should become
Send notifications to more than 65+ services.

I don't see a difference?

**Comment by James-Firth** [comment]
@aptalca Whoops I fixed the typo in both places, my bad. Updated.
